"use client";

import { useMemo, useState } from "react";

const navItems=[["总览","▦"],["账号与用户","◎"],["AI 助手运营","✦"],["行情数据","⌁"],["商机撮合","◇"],["商业化中心","◉"],["风控配置","⚙"]];
const users=[
  {name:"马先生",phone:"138****6612",role:"采购从业者",company:"华冶供应链",employment:"在职已认证",verified:true,focus:"螺纹钢、热卷",source:"微信授权",level:"高意向",active:"刚刚"},
  {name:"李女士",phone:"186****2098",role:"仓储运营人员",company:"金属仓储有限公司",employment:"在职已认证",verified:true,focus:"型钢、有色金属",source:"手机号",level:"活跃用户",active:"12 分钟前"},
  {name:"王先生",phone:"139****8831",role:"大宗贸易从业者",company:"湾区物产",employment:"待验证任职",verified:false,focus:"铜、铝、冷轧",source:"微信授权",level:"跟进中",active:"1 小时前"},
  {name:"周女士",phone:"177****4106",role:"个人采购用户",company:"未填写",employment:"未关联企业",verified:false,focus:"水泥、钢材",source:"本机号码",level:"普通用户",active:"昨天"},
];
const initialOpportunities=[
  {id:"QO20260724018",title:"采购 HRB400E 螺纹钢 10 吨",company:"上海华冶采购",region:"上海",budget:"目标 ¥3,300/吨",serviceFee:"¥19 · PRO",quoteCount:"3 家已报价",status:"已出报价"},
  {id:"QO20260724017",title:"长期采购热轧卷板",company:"华南机械制造",region:"佛山",budget:"月需 800 吨",serviceFee:"¥39 · 基础版",quoteCount:"2 家询价中",status:"询价中"},
  {id:"QO20260724016",title:"寻找有色金属保税仓",company:"湾区物产",region:"广州",budget:"需求 8,000㎡",serviceFee:"¥39 · 基础版",quoteCount:"待匹配供应商",status:"待审核"},
];

function Overview({onNavigate}:{onNavigate:(page:string)=>void}){
  const [published,setPublished]=useState(false);
  return <div className="opsPage"><div className="opsTitle"><div><small>BUSINESS OVERVIEW</small><h2>商业运营总览</h2><p>同时观察会员订阅收入、具体报价订单与撮合履约质量。</p></div><button onClick={()=>setPublished(!published)}>{published?"经营简报已生成 ✓":"生成经营简报"}</button></div>
    <section className="opsKpis">{[["会员订阅 MRR","¥ 38.6万","+18.4%","PRO 会员 3,286 人"],["具体报价订单","1,284","+26.2%","付费转化率 34.8%"],["报价服务收入","¥ 3.9万","+21.7%","会员订单占 62%"],["混合 ARPU","¥ 126","+14.6%","订阅 + 报价服务"]].map(([name,value,rate,note],index)=><article key={name}><header><span>{name}</span><i>{["◉","◇","¥","↗"][index]}</i></header><strong>{value}</strong><footer><b>{rate}</b><span>{note}</span></footer></article>)}</section>
    <section className="opsCapabilityLoop"><header><div><h3>双收费商业闭环</h3><p>内容由 AI 自动生成，运营聚焦服务质量、会员权益与真实报价履约</p></div><span>会员订阅 + 按次报价</span></header><div>{[["快捷登录与偏好","账号认证 · 用户标签","提升激活率","账号与用户"],["AI 行情问答","助手质量 · 用量额度","形成会员价值","AI 助手运营"],["行情与价格预警","数据源 · 异常监控","保障决策可信","行情数据"],["开通 PRO 会员","套餐 · 权益 · 续费","获得订阅收入","商业化中心"],["获取具体报价","付费询价 · 报价核验","获得服务收入","商机撮合"]].map(([client,operation,result,target],index)=><button onClick={()=>onNavigate(target)} key={client}><i>{["◎","✦","⌁","◉","◇"][index]}</i><span><small>客户端</small><b>{client}</b></span><em>→</em><span><small>运营端</small><b>{operation}</b></span><strong>{result} ›</strong></button>)}</div></section>
    <div className="opsOverviewGrid"><article className="opsTrend"><header><div><h3>双收入趋势</h3><p>近 12 周确认收入</p></div><div><span><i/>会员订阅</span><span><i/>报价服务</span></div></header><div className="opsTrendBars">{[38,48,43,62,57,76,69,88,72,94,86,100].map((height,index)=><i style={{height:`${height}%`}} key={index}/>)}</div><footer><span>第 1 周</span><span>第 4 周</span><span>第 8 周</span><span>本周</span></footer></article>
      <article className="opsTodo"><header><h3>今日待办</h3><span>7 项</span></header>{[["核验具体报价","3","高"],["处理超时询价","2","高"],["处理 AI 低分会话","12","中"],["复核会员退款","2","低"]].map(([title,count,level])=><button key={title}><i className={level}/><span><b>{title}</b><small>{count} 个待处理 · {level}优先级</small></span><em>›</em></button>)}</article></div>
    <div className="opsBottomGrid"><article><header><h3>AI 服务质量</h3><button onClick={()=>onNavigate("AI 助手运营")}>进入 AI 助手运营 →</button></header><div className="opsAiQuality"><div><strong>86.4<small>%</small></strong><span>问题解决率</span></div>{[["回答采纳率",82],["引用完整率",91],["风险拦截率",98]].map(([x,n])=><p key={x as string}><span>{x as string}<b>{n as number}%</b></span><i><em style={{width:`${n}%`}}/></i></p>)}</div></article><article><header><h3>热门品种关注</h3><span>实时</span></header>{[["螺纹钢","12,386","+18%"],["热轧卷板","9,642","+12%"],["铜","7,205","+9%"],["铝","5,819","+6%"]].map((x,i)=><div className="opsRank" key={x[0]}><b>0{i+1}</b><span>{x[0]}</span><i style={{width:`${88-i*15}%`}}/><em>{x[1]}</em><small>{x[2]}</small></div>)}</article></div>
  </div>;
}

function CommercializationOps(){
  const [saved,setSaved]=useState(false);
  return <div className="opsPage"><div className="opsTitle"><div><small>MONETIZATION CENTER</small><h2>商业化中心</h2><p>一套账户体系，融合高频会员订阅与低频具体报价服务。</p></div><button onClick={()=>setSaved(true)}>{saved?"计费方案已保存 ✓":"保存计费方案"}</button></div>
    <section className="commercialModelBanner"><div><small>模式 A · 高频价值</small><h3>会员订阅</h3><p>持续使用 AI 深度解读、价格预警等决策能力。</p></div><i>+</i><div><small>模式 B · 结果付费</small><h3>具体报价服务</h3><p>用户选定商机后按次付费，平台交付真实、可核验报价。</p></div><strong>会员可享报价折扣与年付免费额度</strong></section>
    <section className="opsMemberKpis">{[["会员订阅 MRR","¥ 38.6万","续费率 72%"],["PRO 会员","3,286","付费率 11.5%"],["报价服务收入","¥ 3.9万","订单 1,284 笔"],["混合 ARPU","¥ 126","较单订阅 +14.6%"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</section>
    <div className="opsMemberGrid commercialConfig"><article><header><div><h3>会员套餐</h3><p>承担日常高频 AI 决策服务的持续收入</p></div><button>编辑套餐</button></header>{[["基础版","免费","AI 问答 3 次/日 · 预警 3 个"],["PRO 月付","¥99 / 月","不限次 AI 解读 · 预警 20 个"],["PRO 年付","¥899 / 年","月付全部权益 · 报价每月 3 次免费"]].map((x,index)=><div key={x[0]}><i>{index===0?"B":"P"}</i><span><b>{x[0]}</b><small>{x[2]}</small></span><em>{x[1]}</em></div>)}</article><article><header><div><h3>具体报价计费</h3><p>只在用户确认获取真实报价时收费</p></div><button>编辑规则</button></header>{[["基础用户","¥39 / 次","至少 2 家有效报价"],["PRO 会员","¥19 / 次","会员专属 5 折"],["未交付保障","自动退款","2 小时无有效报价"],["年付会员","每月前 3 次免费","超出后 ¥19 / 次"]].map((x,index)=><div key={x[0]}><i>{["¥","P","↺","3"][index]}</i><span><b>{x[0]}</b><small>{x[2]}</small></span><em>{x[1]}</em></div>)}</article></div>
    <section className="commercialFunnel"><header><div><h3>融合转化漏斗</h3><p>会员权益既提升留存，也降低用户第一次购买具体报价的门槛</p></div><span>近 30 天</span></header>{[["AI 活跃用户","28,649","100%"],["触达会员方案","9,860","34.4%"],["开通 PRO","3,286","11.5%"],["发起付费询价","1,284","4.5%"],["获得有效报价","1,126","87.7%"]].map((x,index)=><div key={x[0]}><span><i style={{width:`${100-index*13}%`}}/></span><b>{x[0]}</b><strong>{x[1]}</strong><em>{x[2]}</em></div>)}</section>
  </div>;
}

function RiskConfigOps(){
  const [enabled,setEnabled]=useState([true,true,true]);
  return <div className="opsPage"><div className="opsTitle"><div><small>RISK & PLATFORM RULES</small><h2>风控配置</h2><p>管理 AI 回答、行情数据与具体报价履约的核心安全规则。</p></div><button>新增策略</button></div>
    <section className="opsRiskSummary">{[["AI 风险拦截","98.6%","今日拦截 36 次"],["行情异常识别","99.2%","待处理 2 条"],["报价真实性","96.8%","待核验 3 条"],["退款及时率","99.6%","超时退款 8 笔"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</section>
    <section className="opsRuleList"><header><span>策略名称</span><span>作用于客户端功能</span><span>触发条件</span><span>状态</span><span>操作</span></header>{[["AI 价格建议免责声明","AI 行情问答","涉及价格预测或采购建议"],["行情多源偏差预警","行情、自选、预警","来源价差超过 1.5%"],["具体报价有效性核验","商机报价服务","库存、税费或有效期字段缺失"]].map((x,index)=><div key={x[0]}><span><i>{["✦","⌁","◇"][index]}</i><b>{x[0]}</b></span><span>{x[1]}</span><span>{x[2]}</span><span><button className={enabled[index]?"on":""} onClick={()=>setEnabled(items=>items.map((v,i)=>i===index?!v:v))}><i/></button></span><span><button>配置</button></span></div>)}</section>
  </div>;
}

export default function CommodityAiOps(){
  const [active,setActive]=useState("总览"),[keyword,setKeyword]=useState(""),[opportunities,setOpportunities]=useState(initialOpportunities);
  const filteredUsers=useMemo(()=>users.filter(user=>`${user.name}${user.phone}${user.role}${user.company}${user.focus}`.includes(keyword)),[keyword]);
  const updateOpportunity=(id:string,status:string)=>setOpportunities(list=>list.map(item=>item.id===id?{...item,status}:item));
  return <div className="commodityOps"><aside className="opsSidebar"><div className="opsBrand"><i>AI</i><span><b>大宗智能体</b><small>PLATFORM OPS</small></span></div><nav>{navItems.map(([label,icon])=><button className={active===label?"active":""} onClick={()=>setActive(label)} key={label}><i>{icon}</i>{label}{["账号与用户","商机撮合"].includes(label)&&<em>{label==="账号与用户"?"12":"3"}</em>}</button>)}</nav><div className="opsAccount"><span>M</span><p><b>MADAO</b><small>平台超级管理员</small></p><i>⌄</i></div></aside>
    <main className="opsMain"><header className="opsTop"><div><button>☰</button><span>运营工作台 / <b>{active}</b></span></div><div><button>⌕</button><button className="notice">♢<i>6</i></button><span>2026年7月24日 星期五</span></div></header>
      {active==="总览"&&<Overview onNavigate={setActive}/>}
      {active==="账号与用户"&&<div className="opsPage"><div className="opsTitle"><div><small>ACCOUNT & USER</small><h2>账号与用户运营</h2><p>承接微信授权、本机号登录、个人角色、偏好、自选、可选任职信息与用户画像。</p></div><button>导出用户数据</button></div><div className="opsToolbar"><input value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="搜索姓名、手机号、任职企业或关注品种"/><div><button className="active">全部用户</button><button>今日新增</button><button>任职待验证</button><button>高意向</button></div></div><section className="opsTable"><header><span>个人用户</span><span>登录方式</span><span>角色与偏好</span><span>任职信息</span><span>用户分层</span><span>操作</span></header>{filteredUsers.map(user=><div key={user.phone}><span><i>{user.name.slice(0,1)}</i><b>{user.name}<small>{user.role} · {user.phone}</small></b></span><span>{user.source}</span><span>{user.focus}</span><span><em className={user.verified?"verified":""}>{user.employment}</em><small>{user.company}</small></span><span><b>{user.level}</b><small>{user.active}</small></span><span><button>查看画像</button></span></div>)}</section></div>}
      {active==="AI 助手运营"&&<div className="opsPage"><div className="opsTitle"><div><small>AI ASSISTANT OPERATION</small><h2>AI 助手运营</h2><p>覆盖行情问答、采购需求补全、知识引用与高风险回答质检。</p></div><button>新建 AI 助手</button></div><section className="opsAiCards">{[["大宗采购助手","运行中","今日 8,619 次调用","解决率 89.2%"],["行情分析助手","运行中","今日 6,280 次调用","采纳率 84.6%"],["企业洞察助手","灰度中","今日 1,206 次调用","完成率 78.3%"]].map((x,index)=><article key={x[0]}><header><i>AI</i><span><b>{x[0]}</b><small>模型版本 V{3-index}.2</small></span><em className={index===2?"gray":""}>{x[1]}</em></header><p>{x[2]}</p><strong>{x[3]}</strong><footer><button>会话质检</button><button>配置助手</button></footer></article>)}</section><div className="opsKnowledge"><header><div><h3>行业知识库</h3><p>回答引用与检索使用的结构化行业资料</p></div><button>＋ 上传资料</button></header>{[["钢材行情数据集","行情数据","2 分钟前","126.8 万条","正常"],["采购业务规则库","业务规则","昨天","286 篇","正常"],["产业研报知识库","研究报告","07-22","1,864 篇","更新中"],["风险与合规词库","风控规则","07-20","3,219 条","正常"]].map(x=><div key={x[0]}><i>▤</i><span><b>{x[0]}</b><small>{x[1]} · 更新于 {x[2]}</small></span><em>{x[3]}</em><strong>{x[4]}</strong><button>管理</button></div>)}</div></div>}
      {active==="行情数据"&&<div className="opsPage"><div className="opsTitle"><div><small>MARKET DATA OPERATION</small><h2>行情数据</h2><p>管理现货、期货、品种分类、价格源、指数与客户端预警。</p></div><button>新增价格源</button></div><section className="opsMarketCards">{[["螺纹钢","3,289","-0.19%","上海 · HRB400E"],["热轧卷板","3,486","+0.32%","上海 · Q235B"],["电解铜","78,420","+0.56%","长江现货"],["铝锭","20,680","-0.08%","佛山 · A00"]].map((x,index)=><article key={x[0]}><header><b>{x[0]}</b><span>数据正常</span></header><strong>¥ {x[1]}</strong><em className={x[2].startsWith("+")?"up":""}>{x[2]}</em><p>{x[3]}</p><div>{[36,48,40,62,54,76,68,82].map((n,i)=><i key={i} style={{height:`${n+index*2}%`}}/>)}</div><footer><button>查看数据</button><button>配置预警</button></footer></article>)}</section></div>}
      {active==="商机撮合"&&<div className="opsPage"><div className="opsTitle"><div><small>PAID QUOTE FULFILLMENT</small><h2>商机撮合与具体报价</h2><p>承接用户已付费询价，完成需求核验、供应商询价、报价有效性核验与交付。</p></div><button>报价服务规则</button></div><section className="quoteOpsSummary"><article><span>今日付费询价</span><b>86</b><small>PRO 用户占 62%</small></article><article><span>有效报价交付率</span><b>87.7%</b><small>目标 ≥ 85%</small></article><article><span>平均首报时长</span><b>38 分钟</b><small>较上周 -12 分钟</small></article><article><span>超时自动退款</span><b>8 笔</b><small>退款金额 ¥312</small></article></section><section className="opsOpportunityBoard">{opportunities.map(item=><article key={item.id}><header><span>{item.id}</span><em>{item.status}</em></header><h3>{item.title}</h3><p>{item.company}　·　⌖ {item.region}</p><strong>{item.budget}</strong><div className="quoteOpsMeta"><span>服务费 <b>{item.serviceFee}</b></span><span>{item.quoteCount}</span></div><footer><button>查看报价单</button>{item.status==="待审核"&&<button className="primary" onClick={()=>updateOpportunity(item.id,"询价中")}>核验并询价</button>}{item.status==="询价中"&&<button className="primary" onClick={()=>updateOpportunity(item.id,"已出报价")}>交付具体报价</button>}</footer></article>)}</section></div>}
      {active==="商业化中心"&&<CommercializationOps/>}
      {active==="风控配置"&&<RiskConfigOps/>}
    </main></div>;
}
