"use client";

import { useMemo, useState } from "react";

const navItems=[["总览","▦"],["账号与用户","◎"],["AI 助手运营","✦"],["行情数据","⌁"],["内容与研报","▤"],["商机撮合","◇"],["会员与触达","◉"],["风控配置","⚙"]];
const users=[
  {name:"上海华冶采购",phone:"138****6612",company:"华冶供应链",focus:"螺纹钢、热卷",source:"微信授权",level:"高意向",active:"刚刚"},
  {name:"临沂金属仓配",phone:"186****2098",company:"金属仓储有限公司",focus:"型钢、有色金属",source:"手机号",level:"已认证",active:"12 分钟前"},
  {name:"广州湾区贸易",phone:"139****8831",company:"湾区物产",focus:"铜、铝、冷轧",source:"微信授权",level:"跟进中",active:"1 小时前"},
  {name:"成都建材集采",phone:"177****4106",company:"城建采购中心",focus:"水泥、钢材",source:"本机号码",level:"普通",active:"昨天"},
];
const initialOpportunities=[
  {id:"PO20260723018",title:"采购 HRB400E 螺纹钢 10 吨",company:"上海华冶采购",region:"上海",budget:"¥ 3,300/吨",status:"待审核"},
  {id:"PO20260723017",title:"长期采购热轧卷板",company:"华南机械制造",region:"佛山",budget:"月需 800 吨",status:"待分发"},
  {id:"PO20260723016",title:"寻找有色金属保税仓",company:"湾区物产",region:"广州",budget:"8,000㎡",status:"跟进中"},
];

function Overview({onNavigate}:{onNavigate:(page:string)=>void}){
  const [published,setPublished]=useState(false);
  return <div className="opsPage"><div className="opsTitle"><div><small>GOOD MORNING, MADAO</small><h2>平台运营总览</h2><p>实时掌握用户增长、AI 服务质量与业务转化。</p></div><button onClick={()=>setPublished(!published)}>{published?"今日简报已生成 ✓":"生成今日运营简报"}</button></div>
    <section className="opsKpis">{[["注册用户","28,649","+12.8%","微信授权占 61%"],["日活用户","6,280","+8.4%","自选品种 4.8 个/人"],["AI 有效会话","18,506","+23.7%","回答采纳率 82%"],["商机转化金额","¥ 2,386万","+16.2%","需求补全率 76%"]].map(([name,value,rate,note],index)=><article key={name}><header><span>{name}</span><i>{["◎","↗","✦","◇"][index]}</i></header><strong>{value}</strong><footer><b>{rate}</b><span>{note}</span></footer></article>)}</section>
    <section className="opsCapabilityLoop"><header><div><h3>客户端能力运营闭环</h3><p>从用户动作出发，定位对应的平台运营抓手</p></div><span>APP → 运营端 → 业务结果</span></header><div>{[["快捷登录与偏好","账号认证 · 用户标签","提升激活率","账号与用户"],["AI 行情问答","助手配置 · 会话质检","提升采纳率","AI 助手运营"],["行情与价格预警","数据源 · 异常监控","保障时效准确","行情数据"],["快讯与精选研报","采编审核 · AI 解读","提升内容消费","内容与研报"],["采购需求与推荐","需求审核 · 智能匹配","促进交易转化","商机撮合"],["会员与我的","权益 · 收藏 · 消息触达","提升留存复访","会员与触达"]].map(([client,operation,result,target],index)=><button onClick={()=>onNavigate(target)} key={client}><i>{["◎","✦","⌁","▤","◇","◉"][index]}</i><span><small>客户端</small><b>{client}</b></span><em>→</em><span><small>运营端</small><b>{operation}</b></span><strong>{result} ›</strong></button>)}</div></section>
    <div className="opsOverviewGrid"><article className="opsTrend"><header><div><h3>用户与 AI 会话趋势</h3><p>近 12 小时实时数据</p></div><div><span><i/>活跃用户</span><span><i/>AI 会话</span></div></header><div className="opsTrendBars">{[38,48,43,62,57,76,69,88,72,94,86,100].map((height,index)=><i style={{height:`${height}%`}} key={index}/>)}</div><footer><span>00:00</span><span>06:00</span><span>12:00</span><span>现在</span></footer></article>
      <article className="opsTodo"><header><h3>今日待办</h3><span>8 项</span></header>{[["审核采购商机","3","高"],["处理 AI 低分会话","12","中"],["发布午间行情快讯","1","高"],["更新螺纹钢知识库","2","低"]].map(([title,count,level])=><button key={title}><i className={level}/><span><b>{title}</b><small>{count} 个待处理 · {level}优先级</small></span><em>›</em></button>)}</article></div>
    <div className="opsBottomGrid"><article><header><h3>AI 服务质量</h3><button onClick={()=>onNavigate("AI 助手运营")}>进入 AI 助手运营 →</button></header><div className="opsAiQuality"><div><strong>86.4<small>%</small></strong><span>问题解决率</span></div>{[["回答采纳率",82],["引用完整率",91],["风险拦截率",98]].map(([x,n])=><p key={x as string}><span>{x as string}<b>{n as number}%</b></span><i><em style={{width:`${n}%`}}/></i></p>)}</div></article><article><header><h3>热门品种关注</h3><span>实时</span></header>{[["螺纹钢","12,386","+18%"],["热轧卷板","9,642","+12%"],["铜","7,205","+9%"],["铝","5,819","+6%"]].map((x,i)=><div className="opsRank" key={x[0]}><b>0{i+1}</b><span>{x[0]}</span><i style={{width:`${88-i*15}%`}}/><em>{x[1]}</em><small>{x[2]}</small></div>)}</article></div>
  </div>;
}

function MemberTouchOps(){
  const [sent,setSent]=useState(false);
  return <div className="opsPage"><div className="opsTitle"><div><small>MEMBERSHIP & ENGAGEMENT</small><h2>会员与触达</h2><p>承接客户端“我的”、会员权益、收藏、自选、价格预警与消息通知。</p></div><button onClick={()=>setSent(true)}>{sent?"触达任务已创建 ✓":"新建触达任务"}</button></div>
    <section className="opsMemberKpis">{[["PRO 会员","3,286","续费率 72%"],["自选品种","137,562","人均 4.8 个"],["价格预警","18,920","今日触发 1,286"],["收藏研报","46,381","阅读转化 38%"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</section>
    <div className="opsMemberGrid"><article><header><div><h3>会员权益配置</h3><p>客户端 MADAO PRO 权益及使用限制</p></div><button>编辑权益</button></header>{[["AI 深度行情解读","不限次","已启用"],["价格预警","20 个品种","已启用"],["精选研报","全部可读","已启用"],["商机优先推荐","提前 30 分钟","灰度中"]].map(x=><div key={x[0]}><i>✓</i><span><b>{x[0]}</b><small>{x[1]}</small></span><em>{x[2]}</em></div>)}</article><article><header><div><h3>用户触达计划</h3><p>站内信、微信模板消息与推送</p></div><button>查看全部</button></header>{[["螺纹钢价格跌破目标价","价格预警","即时","1,286 人"],["关注品种午间行情","行情订阅","12:10","4,862 人"],["采购需求收到新报价","商机通知","即时","326 人"],["周度精选研报","内容运营","周五","8,920 人"]].map(x=><div key={x[0]}><span><b>{x[0]}</b><small>{x[1]} · {x[2]}</small></span><em>{x[3]}</em></div>)}</article></div>
  </div>;
}

function RiskConfigOps(){
  const [enabled,setEnabled]=useState([true,true,true,false]);
  return <div className="opsPage"><div className="opsTitle"><div><small>RISK & PLATFORM RULES</small><h2>风控配置</h2><p>管理 AI 回答、行情数据、内容发布与商机撮合的全链路安全策略。</p></div><button>新增策略</button></div>
    <section className="opsRiskSummary">{[["AI 风险拦截","98.6%","今日拦截 36 次"],["行情异常识别","99.2%","待处理 2 条"],["内容审核通过","94.8%","待审核 7 篇"],["商机真实性","92.5%","待核验 3 条"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</section>
    <section className="opsRuleList"><header><span>策略名称</span><span>作用于客户端功能</span><span>触发条件</span><span>状态</span><span>操作</span></header>{[["AI 价格建议免责声明","AI 行情问答","涉及价格预测或采购建议"],["行情多源偏差预警","行情、自选、预警","来源价差超过 1.5%"],["AI 生成内容人工复核","快讯、研报、AI 解读","外发内容包含生成文本"],["商机联系方式脱敏","采购需求、推荐商机","公开展示企业联系人"]].map((x,index)=><div key={x[0]}><span><i>{["✦","⌁","▤","◇"][index]}</i><b>{x[0]}</b></span><span>{x[1]}</span><span>{x[2]}</span><span><button className={enabled[index]?"on":""} onClick={()=>setEnabled(items=>items.map((v,i)=>i===index?!v:v))}><i/></button></span><span><button>配置</button></span></div>)}</section>
  </div>;
}

export default function CommodityAiOps(){
  const [active,setActive]=useState("总览"),[keyword,setKeyword]=useState(""),[opportunities,setOpportunities]=useState(initialOpportunities);
  const filteredUsers=useMemo(()=>users.filter(user=>`${user.name}${user.company}${user.focus}`.includes(keyword)),[keyword]);
  const updateOpportunity=(id:string,status:string)=>setOpportunities(list=>list.map(item=>item.id===id?{...item,status}:item));
  return <div className="commodityOps"><aside className="opsSidebar"><div className="opsBrand"><i>AI</i><span><b>大宗智能体</b><small>PLATFORM OPS</small></span></div><nav>{navItems.map(([label,icon])=><button className={active===label?"active":""} onClick={()=>setActive(label)} key={label}><i>{icon}</i>{label}{["账号与用户","商机撮合"].includes(label)&&<em>{label==="账号与用户"?"12":"3"}</em>}</button>)}</nav><div className="opsAccount"><span>M</span><p><b>MADAO</b><small>平台超级管理员</small></p><i>⌄</i></div></aside>
    <main className="opsMain"><header className="opsTop"><div><button>☰</button><span>运营工作台 / <b>{active}</b></span></div><div><button>⌕</button><button className="notice">♢<i>6</i></button><span>2026年7月23日 星期四</span></div></header>
      {active==="总览"&&<Overview onNavigate={setActive}/>}
      {active==="账号与用户"&&<div className="opsPage"><div className="opsTitle"><div><small>ACCOUNT & USER</small><h2>账号与用户运营</h2><p>承接微信授权、本机号登录、偏好、自选、企业认证与用户画像。</p></div><button>导出用户数据</button></div><div className="opsToolbar"><input value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="搜索用户、企业或关注品种"/><div><button className="active">全部用户</button><button>今日新增</button><button>待认证</button><button>高意向</button></div></div><section className="opsTable"><header><span>用户 / 企业</span><span>登录方式</span><span>偏好与自选</span><span>用户状态</span><span>最近活跃</span><span>操作</span></header>{filteredUsers.map(user=><div key={user.phone}><span><i>{user.name.slice(0,1)}</i><b>{user.name}<small>{user.company} · {user.phone}</small></b></span><span>{user.source}</span><span>{user.focus}</span><span><em>{user.level}</em></span><span>{user.active}</span><span><button>查看画像</button></span></div>)}</section></div>}
      {active==="AI 助手运营"&&<div className="opsPage"><div className="opsTitle"><div><small>AI ASSISTANT OPERATION</small><h2>AI 助手运营</h2><p>覆盖行情问答、采购需求补全、知识引用与高风险回答质检。</p></div><button>新建 AI 助手</button></div><section className="opsAiCards">{[["大宗采购助手","运行中","今日 8,619 次调用","解决率 89.2%"],["行情分析助手","运行中","今日 6,280 次调用","采纳率 84.6%"],["企业洞察助手","灰度中","今日 1,206 次调用","完成率 78.3%"]].map((x,index)=><article key={x[0]}><header><i>AI</i><span><b>{x[0]}</b><small>模型版本 V{3-index}.2</small></span><em className={index===2?"gray":""}>{x[1]}</em></header><p>{x[2]}</p><strong>{x[3]}</strong><footer><button>会话质检</button><button>配置助手</button></footer></article>)}</section><div className="opsKnowledge"><header><div><h3>行业知识库</h3><p>回答引用与检索使用的结构化行业资料</p></div><button>＋ 上传资料</button></header>{[["钢材行情数据集","行情数据","2 分钟前","126.8 万条","正常"],["采购业务规则库","业务规则","昨天","286 篇","正常"],["产业研报知识库","研究报告","07-22","1,864 篇","更新中"],["风险与合规词库","风控规则","07-20","3,219 条","正常"]].map(x=><div key={x[0]}><i>▤</i><span><b>{x[0]}</b><small>{x[1]} · 更新于 {x[2]}</small></span><em>{x[3]}</em><strong>{x[4]}</strong><button>管理</button></div>)}</div></div>}
      {active==="行情数据"&&<div className="opsPage"><div className="opsTitle"><div><small>MARKET DATA OPERATION</small><h2>行情数据</h2><p>管理现货、期货、品种分类、价格源、指数与客户端预警。</p></div><button>新增价格源</button></div><section className="opsMarketCards">{[["螺纹钢","3,289","-0.19%","上海 · HRB400E"],["热轧卷板","3,486","+0.32%","上海 · Q235B"],["电解铜","78,420","+0.56%","长江现货"],["铝锭","20,680","-0.08%","佛山 · A00"]].map((x,index)=><article key={x[0]}><header><b>{x[0]}</b><span>数据正常</span></header><strong>¥ {x[1]}</strong><em className={x[2].startsWith("+")?"up":""}>{x[2]}</em><p>{x[3]}</p><div>{[36,48,40,62,54,76,68,82].map((n,i)=><i key={i} style={{height:`${n+index*2}%`}}/>)}</div><footer><button>查看数据</button><button>配置预警</button></footer></article>)}</section></div>}
      {active==="内容与研报"&&<div className="opsPage"><div className="opsTitle"><div><small>CONTENT & RESEARCH</small><h2>内容与研报</h2><p>管理客户端快讯、行情解读、精选研报、收藏与 AI 解读。</p></div><button>＋ 新建内容</button></div><div className="opsContentTabs"><button className="active">全部内容 286</button><button>快讯 128</button><button>行情解读 86</button><button>研报 72</button></div><section className="opsContentList">{[["螺纹钢现货承压，淡季库存小幅回升","行情解读","已发布","MADAO","12:06"],["华东主流钢厂今日调价信息汇总","快讯","已发布","行情编辑组","11:42"],["2026 年下半年钢材供需格局展望","行业研报","待审核","研究院","10:18"],["铜价高位震荡，关注海外库存变化","行情解读","草稿","AI 辅助生成","09:35"]].map(x=><article key={x[0]}><i>▤</i><span><b>{x[0]}</b><small>{x[1]} · {x[3]} · {x[4]}</small></span><em>{x[2]}</em><button>编辑</button><button>⋯</button></article>)}</section></div>}
      {active==="商机撮合"&&<div className="opsPage"><div className="opsTitle"><div><small>OPPORTUNITY MATCHING</small><h2>商机撮合</h2><p>承接 AI 补全后的采购需求，完成审核、供应商匹配、报价与成交跟踪。</p></div><button>商机分发规则</button></div><section className="opsOpportunityBoard">{opportunities.map(item=><article key={item.id}><header><span>{item.id}</span><em>{item.status}</em></header><h3>{item.title}</h3><p>{item.company}　·　⌖ {item.region}</p><strong>{item.budget}</strong><footer><button>查看详情</button>{item.status==="待审核"&&<button className="primary" onClick={()=>updateOpportunity(item.id,"待分发")}>审核通过</button>}{item.status==="待分发"&&<button className="primary" onClick={()=>updateOpportunity(item.id,"跟进中")}>智能分发</button>}</footer></article>)}</section></div>}
      {active==="会员与触达"&&<MemberTouchOps/>}
      {active==="风控配置"&&<RiskConfigOps/>}
    </main></div>;
}
